version: '3'
services:
  mqserver:
    image: rabbitmq:management
    ports:
      - "5671:5671" # AMQP 0-9-1 and 1.0
      - "5672:5672" # AMQP 0-9-1 and 1.0
      - "15672:15672" # Management WebUI
  python:
    build: ./python
    depends_on:
      - mqserver
  go:
    build: ./go
    depends_on:
      - mqserver